apiVersion: apps/v1
kind: Deployment
metadata: ##(metedata) 
  name: nginx-deployment
spec: ##(specification)
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec: ##for pods
      containers:
      - name: nginx
        image: nginx:1.16
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
