apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: dk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dk
  template:
    metadata:
      labels:
        app: dk
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dk-service
spec:
  selector:
    app: dk
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80